services:
  - type: web
    name: orcamentos
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class gevent --workers 2 --worker-connections 500 --timeout 120 --keep-alive 5
    envVars:
      - key: DATABASE_URL
        sync: false
